from __future__ import annotations

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=2000, description="User input message")


class ChatResponse(BaseModel):
    response: str = Field(..., description="Short response generated by Bengoshi")
    status: str = Field(default="success")


class HealthResponse(BaseModel):
    status: str = Field(default="ok")
    app_name: str = Field(default="Bengoshi")
    version: str = Field(default="0.1.0")
